version: "3.7"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shadow_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./images:/usr/src/app/images
      - ./logs:/usr/src/app/logs
